// ── aspect-voice.js ──
// Extracted from index.html — Phase 0 mechanical extraction.
// ASPECT_NATURE and NATAL_ASPECT_DEPTH constants.

const ASPECT_NATURE={
  'conjunction':{glyph:'☌',color:'var(--gold)',nature:'Fusion. The two planets blend into a single current — their themes cannot be separated. Powerful but sometimes lacks perspective.'},
  'opposition':{glyph:'☍',color:'var(--crimson)',nature:'Polarity. The two planets face each other across the chart — themes show up as tension, mirroring, or projection onto others, demanding integration.'},
  'trine':{glyph:'△',color:'var(--emerald)',nature:'Ease. The planets share an element and flow together freely — talent, often unconscious, can be taken for granted.'},
  'square':{glyph:'□',color:'var(--crimson)',nature:'Friction. The planets share modality but clash by element — tension that forces growth through crisis and effort.'},
  'sextile':{glyph:'⚹',color:'var(--emerald)',nature:'Opportunity. Planets in complementary elements — cooperation available if you reach for it, but not automatic.'},
  'quincunx':{glyph:'⚻',color:'var(--amber)',nature:'Adjustment. Planets in unrelated signs — themes never quite fit and require constant recalibration, often tied to health or habit.'},
  'semi-sextile':{glyph:'⚺',color:'var(--text2)',nature:'Subtle tension. Adjacent signs — quiet irritation or awkward transitions between themes.'}
};
const NATAL_ASPECT_DEPTH={
  'Sun-Moon|conjunction':'Inner life and outer identity fused — wholeness, but less inner dialogue. Born near a new moon.',
  'Sun-Moon|opposition':'Will and feeling pull against each other. Born near a full moon — a life of negotiating between what you want and what you need.',
  'Sun-Moon|square':'Tension between conscious direction and emotional nature. Family-of-origin patterns often replay until integrated.',
  'Sun-Moon|trine':'Ego and feeling cooperate. Rest comes easily; a settled core.',
  'Sun-Moon|sextile':'Purpose and emotion support each other when you act.',
  'Sun-Mercury|conjunction':'Identity and thought merge. Strong voice, but can over-identify with opinions.',
  'Sun-Venus|conjunction':'Love, art, and value fuse with identity — charm, vanity, or aesthetic sense as a life theme.',
  'Sun-Mars|conjunction':'Willpower amplified — drive, courage, or a chip on the shoulder. Cauldron of initiative.',
  'Sun-Mars|square':'Will clashes with drive. Anger and assertion must be trained rather than suppressed.',
  'Sun-Jupiter|trine':'Natural confidence, optimism, protection. Opportunities find you.',
  'Sun-Jupiter|square':'Overconfidence or overextension. Faith outpaces capacity until tempered.',
  'Sun-Saturn|conjunction':'Authority and self fused — heavy responsibility from early on, maturity accelerated, father-theme intense.',
  'Sun-Saturn|square':'Self-worth is tested. Achievement through discipline, but prone to self-doubt.',
  'Sun-Saturn|trine':'Quiet competence. Enduring structure. Good with long horizons.',
  'Sun-Saturn|opposition':'You measure yourself against external authority — until you become your own.',
  'Sun-Uranus|conjunction':'Lightning identity. Radically individual, prone to disruption of stable forms.',
  'Sun-Uranus|square':'Rebellion as reflex. Must learn to channel eccentricity productively.',
  'Sun-Neptune|conjunction':'Porous self. Artistic, mystical, but identity can dissolve in others\' fantasies.',
  'Sun-Neptune|square':'Confusion about who you are. Disillusionment as teacher.',
  'Sun-Pluto|conjunction':'Intense will, survivor\'s edge. Power dynamics are a core theme.',
  'Sun-Pluto|square':'Power struggles with authority, especially fathers. Transformation through crisis.',
  'Moon-Mercury|conjunction':'Feelings and thoughts fused — you think your way through moods, speak from the heart.',
  'Moon-Venus|trine':'Emotional warmth, aesthetic comfort, easy relating.',
  'Moon-Mars|square':'Quick temper, emotional volatility. Must learn to feel before reacting.',
  'Moon-Jupiter|trine':'Emotional abundance, faith, generosity. Protected instincts.',
  'Moon-Saturn|conjunction':'Emotional gravity. Mother-theme strict or absent. Feelings kept under discipline.',
  'Moon-Saturn|square':'Emotional loneliness until self-parented. Slow to trust, but steady once bonded.',
  'Moon-Uranus|square':'Emotional restlessness. Sudden mood shifts, fear of being tied down.',
  'Moon-Neptune|conjunction':'Dream-soaked feelings, psychic porousness, compassionate but prone to self-deception.',
  'Moon-Pluto|square':'Obsessive emotional undercurrents. Emotional crises as transformation.',
  'Mercury-Venus|conjunction':'Graceful speech, artistic thought, diplomatic voice.',
  'Mercury-Mars|conjunction':'Sharp mind, quick tongue, argumentative edge.',
  'Mercury-Jupiter|opposition':'Big ideas vs. detail. Teacher-student dynamic between local and far.',
  'Mercury-Saturn|conjunction':'Disciplined, serious mind. Slow but deep; prone to self-criticism about intellect.',
  'Mercury-Uranus|trine':'Quick, original mind. Insight arrives whole.',
  'Mercury-Neptune|square':'Confusion between imagination and fact. Must fact-check intuitions.',
  'Mercury-Pluto|conjunction':'Penetrating mind, research instinct, speaks hidden things.',
  'Venus-Mars|conjunction':'Desire and attraction fused — passionate, magnetic, sometimes volatile in love.',
  'Venus-Mars|square':'Love and desire pull different directions. Relationship tension as teacher.',
  'Venus-Mars|trine':'Attraction flows easily; creative and romantic currents cooperate.',
  'Venus-Jupiter|conjunction':'The great benefic — grace, generosity, aesthetic abundance.',
  'Venus-Saturn|conjunction':'Love tested by time and responsibility. Slow to open, loyal once committed.',
  'Venus-Saturn|square':'Feeling unworthy of love, or attracted to distant/older partners. Earned affection.',
  'Venus-Uranus|square':'Sudden attractions, unstable affections, freedom vs. intimacy.',
  'Venus-Neptune|conjunction':'Idealized love, artistic sensitivity, disillusionment cycles.',
  'Venus-Pluto|square':'Intense attachments, jealousy, transformative relationships.',
  'Mars-Jupiter|trine':'Action blessed with luck. Enthusiasm and courage.',
  'Mars-Saturn|conjunction':'Disciplined drive — blacksmith energy. Hard-won competence, frustration if blocked.',
  'Mars-Saturn|square':'Effort meets obstacle. Anger frozen or delayed. Forges resilience.',
  'Mars-Uranus|square':'Accident-prone or electric action. Sudden moves, impatience.',
  'Mars-Neptune|square':'Drive clouded by confusion. Misplaced anger, or effort that dissolves.',
  'Mars-Pluto|conjunction':'Volcanic drive, survivor\'s force, intensity in anything pursued.',
  'Jupiter-Saturn|conjunction':'The great chronocrator — structure meets expansion. Ambition built carefully. A generational signature.',
  'Jupiter-Saturn|opposition':'Faith vs. fear, growth vs. limit. Lifetime teacher-aspect.',
  'Jupiter-Uranus|trine':'Sudden breakthroughs, lucky timing with innovation.',
  'Jupiter-Neptune|conjunction':'Mystical faith, visionary but prone to inflation.',
  'Jupiter-Pluto|square':'Outsized ambition, hunger for power or meaning.',
  'Saturn-Uranus|square':'Tradition vs. revolution. Breaking and rebuilding as life-theme.',
  'Saturn-Neptune|square':'Structure dissolves under doubt. Faith tested by reality.',
  'Saturn-Pluto|conjunction':'Heavy generational weight, endurance forged through loss.',
  'Uranus-Neptune|sextile':'Generational: spiritual innovation, visionary technology.',
  'Uranus-Pluto|square':'Generational: revolution, systemic upheaval. 1960s/2010s.',
  'Sun-Ascendant|conjunction':'Identity matches presentation. What you are shows.',
  'Moon-Ascendant|conjunction':'Feeling shows on the surface. Emotionally transparent body.',
  'Mars-Ascendant|conjunction':'Assertive presence, athletic bearing, scar on the face common.',
  'Saturn-Ascendant|conjunction':'Serious appearance, aged early, gravitas.',
  'Sun-MC|conjunction':'Vocation aligned with identity. Publicly visible life.',
  'Saturn-MC|conjunction':'Career-defining authority, slow-climbing ambition.'
};
