// ── natal-voice.js ──
// Extracted from index.html — Phase 0 mechanical extraction.
// Natal point interpretation voice corpus.

const NATAL_VOICE={
Sun:{title:'Your Core Self',desc:'Your Sun in Cancer in the 4th house places your core identity in the realm of home, family, and emotional roots. You find yourself through nurturing, creating safe spaces, and honoring where you come from. Your deepest sense of purpose is tied to emotional connection and protecting what matters to you. Transits here shake your foundations — they touch not just who you are but where you belong.'},
Moon:{title:'Your Inner World',desc:'Your Moon in Capricorn in the 11th house — in detriment — creates a tension between your emotional needs and how you express them. You feel deeply but process emotions through structure, discipline, and achievement. In the 11th house, your emotional security is tied to your community, friendships, and vision for the future. You nurture others through practical support rather than overt warmth. Transits here challenge your emotional self-reliance.'},
Mercury:{title:'Your Mind',desc:'Your Mercury in Gemini in the 4th house — in domicile — gives you an exceptionally quick, curious, and versatile mind operating at full power. You process information rapidly, see connections others miss, and communicate with natural wit. In the 4th house, your thinking is deeply influenced by your upbringing, family narratives, and private inner world. Transits here accelerate or disrupt your mental patterns.'},
Venus:{title:'Your Heart & Values',desc:'Your Venus in Gemini in the 3rd house expresses love through communication, intellectual connection, and variety. You are attracted to people who stimulate your mind and keep you curious. In the 3rd house, daily interactions, conversations, and your immediate environment are where you experience beauty and pleasure. Transits here shift your relationship dynamics and what you find attractive.'},
Mars:{title:'Your Drive',desc:'Your Mars in Gemini in the 3rd house channels your drive through words, ideas, and mental agility. You fight with your mind — debating, persuading, and outmaneuvering rather than overpowering. Your energy scatters across multiple interests simultaneously. In the 3rd house, you take action through communication, short trips, and your daily environment. Transits here fuel or frustrate your ambitions.'},
Jupiter:{title:'Your Growth',desc:'Your Jupiter in Capricorn in the 10th house — in fall — means your growth and expansion come through disciplined effort in your career rather than easy luck. Jupiter struggles in Capricorn, so abundance arrives through hard work, patience, and building lasting structures. In the 10th house, your career and public reputation are where you seek meaning and expansion. Transits here amplify professional ambitions.'},
Saturn:{title:'Your Foundation',desc:'Your Saturn in Aries in the 1st house — in fall — places your greatest life lesson directly in your identity and self-assertion. Saturn struggles in Aries, creating tension between the need for caution and the impulse to act. In the 1st house, you may have felt restricted in expressing yourself early in life, developing discipline around who you are. Transits here test your identity at the deepest structural level.'},
Uranus:{title:'Your Individuality',desc:'Your Uranus in Aquarius in the 11th house — in domicile — is at full revolutionary power in its home sign and natural house. Your individuality expresses through progressive ideas, unconventional friendships, and a vision for the future that others find radical. You are naturally drawn to communities of innovators and outsiders. Transits here electrify your social world and accelerate your most authentic impulses.'},
Neptune:{title:'Your Imagination',desc:'Your Neptune in Capricorn in the 11th house brings your dreams and spiritual longings into the realm of community and long-term vision. You idealize social progress and may have illusions about institutions or authority figures within your groups. Your imagination works best when given practical structure. Transits here blur the boundaries between your individual dreams and collective aspirations.'},
Pluto:{title:'Your Deepest Power',desc:'Your Pluto in Sagittarius in the 8th house — Pluto\'s natural house — concentrates your transformative power in the deepest possible position. Intimacy, shared resources, psychological depths, and matters of life and death are where you encounter your shadow and reclaim your power. In Sagittarius, your transformations are tied to belief systems, philosophical crises, and the search for meaning. Transits here go to the absolute core.'},
Chiron:{title:'Your Deepest Wound',desc:'Your Chiron in Libra in the 7th house places your core wound in relationships, partnerships, and the balance between self and other. You may have experienced early wounds around fairness, belonging, or feeling truly seen by a partner or close ally. People-pleasing and conflict avoidance are shadow expressions. The gift: your pain around these themes makes you an exceptional mediator, counselor, and bridge-builder — someone who helps others navigate their own relational wounds with rare empathy and grace.'},
NorthNode:{title:'Your Soul Path',desc:'Your North Node in Libra in the 7th house points your soul\'s evolution directly toward partnership, balance, diplomacy, and learning through relationships. Your growth comes from moving away from self-reliance (South Node in Aries/1st house) toward genuine collaboration, compromise, and seeing yourself through the mirror of others. Committed partnerships are your evolutionary classroom.'},
Ascendant:{title:'Your Outer Self',desc:'Your Pisces Ascendant gives you a gentle, empathetic, and slightly ethereal presence. Others perceive you as sensitive, artistic, and adaptable — sometimes hard to pin down. You approach new situations intuitively rather than strategically, absorbing the energy of your environment. Your physical appearance may have a dreamy or otherworldly quality. Transits here change how the world sees you and how you instinctively engage with it.'},
MC:{title:'Your Public Life',desc:'Your Midheaven in Sagittarius at the cusp of Capricorn points your career toward exploration, teaching, philosophy, or cross-cultural work — with a pragmatic Capricorn edge that demands tangible results. Your public reputation is tied to big-picture thinking and expanding others\' horizons. You need work that feels meaningful and expansive, not just profitable. Transits here are major career turning points.'},
};
