// ── references.js ──
// Extracted from index.html — Phase 0 mechanical extraction.
// REF_USEFUL and REFERENCES constants (Lore tab data).

const REF_USEFUL={
  'Zodiacal Releasing':{whenItMatters:'In long-arc career and identity questions. The chapters do not predict events as much as define the question being asked of you for that span.',howToRead:'Locate which sign is currently ruling. The ruler\'s natal condition (sign, house, dignity, aspects) describes the texture of the period. Peak L1 periods correspond to maximum visibility; Loosings mark forced reorientation.',watchFor:'Major peak years and the eight-from-eight Loosing of the Bond — these are the structural turning points, not random transits.'},
  'Firdaria':{whenItMatters:'When you want a steady year-by-year throughline for the whole life. Useful as a backdrop to ZR — Firdaria says who is in charge for the next ~10 years; ZR says what episode is playing.',howToRead:'Read the major-period planet through its natal placement and its relationship to the sect light. Sub-period planet adds the flavour for the current ~1–2 years.',watchFor:'Sub-period transitions every 1–2 years — they tend to land as quiet shifts in mood or focus, not events.'},
  'Solar Return':{whenItMatters:'Once a year around your birthday. Read it as the keynote chart for the next 12 months.',howToRead:'Look at the SR Ascendant (whole-sign), the houses of the SR Sun and Moon, and any tight aspects to natal points. Profected lord placement in the SR is the year\'s headline.',watchFor:'A SR chart cast for your current location, not your birthplace. Where you are at the moment of return matters.'},
  'Lunar Return':{whenItMatters:'Each lunar month, useful for short-arc planning and emotional weather forecasting.',howToRead:'Note the LR Ascendant and Moon house. The placement of the LR Moon\'s ruler shows where the month\'s feeling will be processed.',watchFor:'Don\'t over-weight a single LR — they swing too fast. Use as one signal among several.'},
  'Annual Profection':{whenItMatters:'Every birthday. The simplest, most reliable timing tool — start here before more complex techniques.',howToRead:'Count one sign per year of age from the natal Ascendant. The sign reached gives the topic (its house) and a Year Lord (its planetary ruler). The Year Lord\'s natal condition + current transits = the year\'s plot.',watchFor:'Year Lord transits, especially returns and stations, tend to land hard during the profected year.'},
  'Planetary Hours':{whenItMatters:'When choosing the moment for a deliberate action — sending an important message, opening a conversation, beginning a piece of work.',howToRead:'Match the action to the hour ruler\'s nature: Mercury for communication, Venus for art and reconciliation, Mars for confrontation, Jupiter for big asks, Saturn for grinding focus. The day ruler colours the whole day; the hour ruler the next ~60 minutes.',watchFor:'Hours change at sunrise and sunset, so the first daytime hour is always the day\'s ruler. Don\'t use clock-hours.'},
  'Electional Astrology':{whenItMatters:'Before any deliberate beginning that will have ongoing consequences — a launch, a contract, a journey.',howToRead:'Pick a moment whose hour-ruler matches the work, with the Moon waxing and not void, and the planet most important to the work strong by sign and house. Avoid stations and tight malefic aspects.',watchFor:'Don\'t let perfect be the enemy of good. A clean Moon condition and a sympathetic hour matter more than chasing every detail.'},
  'Sect':{whenItMatters:'In every chart reading. Sect determines who the helpers and challengers are.',howToRead:'Day chart: Sun is sect light, Jupiter is sect benefic, Mars is out-of-sect malefic. Night chart: reverse — Moon, Venus, Saturn. The in-sect benefic helps cleanly; the out-of-sect malefic causes the bigger trouble.',watchFor:'Modern textbooks often skip sect. It is the single most-overlooked piece of usable Hellenistic doctrine.'},
  'Lot of Fortune':{whenItMatters:'Body, money, daily circumstance, the field of luck. Read alongside the 2nd house and the Moon for material questions.',howToRead:'Note its house and any planets aspecting. Transits to Fortune correspond to shifts in income, health, or living circumstance more reliably than to inner life.',watchFor:'Use the correct sect formula. Day: Asc + Moon − Sun. Night: Asc + Sun − Moon.'},
  'Lot of Spirit':{whenItMatters:'Career, vocation, deliberate action, the field of agency. Pair with the 10th house and the sect light for vocation questions.',howToRead:'Spirit is what the soul chooses to do; Fortune is what happens to the body. Spirit\'s house = arena of intentional action; its ruler\'s condition = the agency available.',watchFor:'When Spirit and Fortune are in dialogue (aspecting each other), action and circumstance are unusually well-aligned.'},
  'Seven Hermetic Lots':{whenItMatters:'When you want a richer cartography of psychic functions than just Fortune and Spirit. Each lot is a calculated point representing a specific theme.',howToRead:'Read each lot in its house, then by aspects to its position. Eros = what attracts you; Necessity = what binds you; Courage = where you push past fear; Victory = where success comes; Nemesis = where the trap is.',watchFor:'Don\'t overload a reading with all seven. Pick the two or three most relevant to the question.'},
  'Lunar Mansions':{whenItMatters:'For lunar electional work and for fine-grained Moon transits. The 28 mansions slice the Moon\'s nightly travel, ~12°51\' each.',howToRead:'Note the mansion the Moon currently occupies. Each has traditional indications (favourable for X, unfavourable for Y) drawn from Picatrix and Manāzil traditions.',watchFor:'The Moon spends ~24 hours in each mansion, so the indication shifts daily. Useful for choosing which day in a week to act.'},
  'Picatrix Faces (Decans)':{whenItMatters:'For finer-grained reading of any planet. Each 30° sign breaks into three 10° decans, each ruled by a different planet in Chaldean order.',howToRead:'In this app the decans are presented through their Golden Dawn / Crowley tarot attributions — the minor arcana 2-10 of each suit map to one decan apiece. The card is a vehicle for the planet-in-sign quality of that 10° slice.',watchFor:'The decan ruler often matters more than the sign ruler for understanding why a planet feels off — e.g., Sun in late Pisces (Mars decan) bites in a way Sun in early Pisces (Saturn decan) does not.'},
  'Essential Dignities':{whenItMatters:'Whenever a planet feels weak or strong and you want to know why. Dignity is structural condition — independent of aspects.',howToRead:'Domicile = home; Exaltation = honoured guest; Detriment = stranger in hostile territory; Fall = exiled. Triplicity, term, and face add finer scoring. A planet in dignity does its job; in detriment/fall it struggles regardless of how well-aspected.',watchFor:'A dignified malefic is still a malefic — Saturn in Capricorn is harsh and effective. A debilitated benefic still helps but with less reach.'},
  'Void of Course Moon':{whenItMatters:'Before initiating anything that needs to grow — a meeting, a contract, a new project, a message expecting reply.',howToRead:'If the Moon will perfect no further Ptolemaic aspect before changing sign, she is void. Traditionally: nothing comes of plans launched here. They drift, fizzle, or get reabsorbed.',watchFor:'Routine and continuation are fine on a void Moon. The doctrine targets new beginnings only.'},
  'Peak Period (ZR)':{whenItMatters:'In Zodiacal Releasing, when a sub-period reaches an angle (1, 4, 7, 10) from the start. Peak periods are when the chapter\'s themes go public.',howToRead:'Peak L1s are career-defining stretches. Peak L2s within a non-peak L1 are smaller crests — the kind of months where things show up.',watchFor:'Not every peak is positive. The texture depends on the ruler\'s natal condition. A weak ruler at peak can mean visible failure as easily as visible success.'},
  'Loosing of the Bond':{whenItMatters:'When ZR jumps to the 9th sign because the next sub-period would fall in the 8th. These are forced reorientations.',howToRead:'Expect a structural break — relationship, vocation, location, identity. Loosings rewrite the chapter, they do not just colour it.',watchFor:'Loosings often coincide with what feels like external disruption but is structural. Don\'t fight the rerouting.'},
  'Benefic / Malefic':{whenItMatters:'In every aspect read. Benefic-malefic mixing tells you whether a configuration helps or hurts.',howToRead:'Jupiter and Venus help; Mars and Saturn obstruct. Sect modifies: in-sect malefic is workable, out-of-sect malefic is the real trouble. Mercury and Moon flex by company.',watchFor:'Modern psychological astrology often denies the malefic/benefic distinction. The traditional reading is more useful for predictive work.'},
  'Retrograde':{whenItMatters:'Whenever a planet is moving backward by apparent motion. Mercury retrogrades ~3-4 times a year for ~3 weeks each; Venus and Mars rarely but for longer. Outer planets retrograde annually for months.',howToRead:'The planet\'s significations turn inward: re-do, re-think, re-encounter. Old situations and people resurface for completion or reconsideration. Mercury Rx disrupts logistics and communication; Venus Rx re-examines relationships and values; Mars Rx stalls initiative and redirects aggression inward.',watchFor:'Retrograde does not invalidate action — it invalidates the assumption that action will move forward in a straight line. The station (the days when the planet appears to stop) is often more disruptive than the retrograde itself. Watch the shadow period: the degrees the planet will retrace are sensitised before the retrograde begins.'},
  'Sect Light':{whenItMatters:'In every chart. The sect light is the chart\'s primary luminary and a key indicator of vitality and direction.',howToRead:'Sun for day birth, Moon for night birth. Its sign, house, and condition outweigh the other luminary for life-direction questions.',watchFor:'Modern readings that lead with the Sun in night charts miss the Moon\'s structural priority.'},
  'Hellenistic Astrology':{whenItMatters:'When you want the original system that everything else descends from — sect, lots, time-lord techniques, whole-sign houses.',howToRead:'Read with sect and whole-sign houses. Lots are first-class objects, not curiosities. Time-lord techniques (profections, ZR, firdaria) sit on top of natal indication.',watchFor:'Hellenistic does not mean outdated — it is the densest and most predictive layer of Western astrology.'},
  'Perso-Arabic Astrology':{whenItMatters:'For mundane and annual techniques (firdaria, world revolutions) and for lots beyond Fortune and Spirit.',howToRead:'Treat as a refinement and elaboration of the Hellenistic system rather than a replacement. Most techniques modern astrologers use as "traditional" come through this layer.',watchFor:'The translations are uneven. Some Latinised Arabic terms have lost meaning across two language jumps.'},
  'Picatrix':{whenItMatters:'When working with talismanic magic, planetary hours, mansions, or decans for ritual/electional purposes.',howToRead:'It is a magical handbook, not a natal text. Its decan and mansion images are tools for talisman-making and psychic reorientation, not personality readings.',watchFor:'In this app the decans are presented through tarot, not Picatrix images — the underlying planetary attribution is the same.'},
  'Hermetic Tradition':{whenItMatters:'Mostly as the source of lots, decans, and the philosophical frame around astrology as a sympathetic art.',howToRead:'Hermetic doctrine sees the chart as a single living configuration mirroring a soul. Useful as a reading posture even when the techniques themselves are pre- or post-Hermetic.',watchFor:'The Hermetic Corpus itself is mostly philosophy, not practical astrology. The astrology is in the Liber Hermetis and attributions.'},
  'Medieval Latin Astrology':{whenItMatters:'For horary, electional, and the older predictive frame that William Lilly summarised.',howToRead:'Use whole-sign or quadrant houses depending on the technique. The dignities table is the central diagnostic tool.',watchFor:'Medieval texts are dense with technical detail and easy to misapply. Lilly\'s Christian Astrology is the readable entry point.'},
  'Vettius Valens':{whenItMatters:'When working with Zodiacal Releasing, lots, or worked-example case material.',howToRead:'Valens shows you how he reasons about real charts. The Anthology is a working astrologer\'s notebook, not a textbook.',watchFor:'Translations vary. Schmidt\'s Project Hindsight edition is the most rigorous; Riley\'s online translation is the most accessible.'},
  'Abū Maʿshar (Albumasar)':{whenItMatters:'For firdaria, mundane techniques, and the medieval transmission of Hellenistic doctrine.',howToRead:'His Great Introduction is the canonical source. Firdaria sequence and rulerships of years come from him.',watchFor:'His mundane work focuses on world events. For natal application, use the firdaria and dignities and skip the world-historical apparatus.'},
  'Guido Bonatti':{whenItMatters:'For horary, electional, and a comprehensive single-author medieval reference.',howToRead:'Liber Astronomiae is encyclopaedic — read by topic, not cover to cover.',watchFor:'Translations are partial. Dykes\' English edition is the working standard.'},
  'William Lilly':{whenItMatters:'For horary practice and for the void-of-course Moon doctrine.',howToRead:'Christian Astrology is structured pedagogically — it teaches the technique, not just the lore. Read for the worked horary examples.',watchFor:'Lilly\'s aspect orbs are wider than modern Hellenistic practice. His void doctrine is stricter than modern usage.'},
  'Hermes Trismegistus':{whenItMatters:'As the legendary attribution for lots, decans, and much of the talismanic apparatus.',howToRead:'Read the attribution as cultural signal — texts assigned to Hermes are claiming a particular lineage and authority. The actual authors are usually anonymous Hellenistic astrologers.',watchFor:'Don\'t treat the Hermes attribution as historical fact. The figure is a syncretic conflation of Hermes and Thoth.'},
  'Whole-Sign Houses':{whenItMatters:'In every natal chart reading. The house system determines which topics a planet rules — switching systems can reassign planets to different houses entirely.',howToRead:'Count signs from the Ascendant sign: the Ascendant sign is the 1st house, the next sign the 2nd, and so on. The degree of the Ascendant marks the rising point but does not define where houses begin. Every planet in that sign is in that house, period.',watchFor:'This app uses whole-sign houses throughout. If you are used to Placidus, some planets may appear in different houses than you expect — especially at high latitudes where Placidus houses become distorted.'},
  'Fixed Stars':{whenItMatters:'When a natal or transiting planet is within about 1 degree of a major star. The tighter the conjunction, the more vivid the effect.',howToRead:'Each star has a traditional planetary nature — e.g., Regulus (Jupiter-Mars) confers ambition and leadership; Algol (Saturn-Jupiter) warns of obsessive extremes. A planet conjunct a star takes on the star\'s coloring in addition to its own.',watchFor:'Fixed stars precess about 1 degree every 72 years, so their zodiacal positions shift over centuries. This app accounts for precession. Only conjunctions matter — no aspects to stars.'},
  'Applying and Separating Aspects':{whenItMatters:'In every transit and natal aspect reading. The distinction tells you whether an influence is building or fading.',howToRead:'Applying: the faster planet is closing in on exact aspect — the event or feeling is approaching, gathering force. Separating: the aspect already perfected — the peak has passed and the energy is dissipating. In horary, applying aspects signify events that will happen; separating ones describe what already has.',watchFor:'An aspect that is applying but very wide (say 8 degrees) may never perfect if the faster planet changes sign first. This is called refranation — a promise that falls through.'},
  'Dignity Scoring':{whenItMatters:'When assessing how effectively a planet can deliver its significations. A planet in strong dignity acts with authority; one in debility struggles or distorts.',howToRead:'Domicile (+5) = the planet is at home and acts naturally. Exaltation (+4) = honoured and elevated. Triplicity (+3), Term (+2), Face (+1) = lesser dignities that add comfort. Detriment (-5) and Fall (-4) = the planet is structurally weakened. Total the score for a quick strength snapshot.',watchFor:'Dignity is not the same as beneficence. A dignified Mars is still Mars — it cuts cleanly rather than clumsily, but it still cuts. A debilitated Jupiter still tries to help but overreaches or disappoints.'},
  'Orbs':{whenItMatters:'When deciding whether an aspect is active. A conjunction at 0 degrees 15 minutes is more potent than one at 9 degrees — orbs quantify that difference.',howToRead:'Traditional practice assigns orbs to planets: the Sun radiates influence across ~15 degrees, the Moon ~12 degrees, others ~7-8 degrees. An aspect is "in orb" when the sum of both planets\' moieties covers the angular distance. Modern practice often uses simpler aspect-based orbs (e.g., 8 degrees for a conjunction, 6 for a trine).',watchFor:'This app uses moderate orbs. If you see an aspect listed as "wide," it is at the edge of effectiveness — real but muted. Exact aspects within 1 degree are the ones that define the chart.'},
  'Synastry':{whenItMatters:'When comparing two charts for compatibility — romantic, business, or familial. It maps where two people\'s planetary energies overlap, clash, or amplify.',howToRead:'Look for conjunctions between one person\'s personal planets (Sun, Moon, Venus, Mars, Mercury) and the other\'s. Harmonious aspects (trine, sextile) flow easily; hard aspects (square, opposition) create friction that can be generative or destructive. Check each person\'s 7th house ruler in the other\'s chart for the relationship\'s structural fit.',watchFor:'Synastry shows dynamics, not outcomes. A chart full of trines can be pleasant but stagnant; a chart with squares generates energy. The question is whether the friction is productive.'},
  'Derived Houses':{whenItMatters:'When asking about someone else through your own chart — your partner\'s finances (8th = their 2nd), your child\'s education (7th from 5th = 11th), your employer\'s stability (4th from 10th = 1st).',howToRead:'Turn the chart so the relevant house becomes "their 1st house," then count forward. The technique works best in horary but can add depth to natal readings when asking specific relational questions.',watchFor:'Don\'t overrotate. Derived houses are useful for pointed questions, but reading every house as someone else\'s something quickly becomes noise. Use when you have a specific question about a specific person.'},
};
// Each entry: {category, term, summary, source, lineage}
// Categories: Technique, Object, Concept, Tradition, Figure
const REFERENCES=[
  // TECHNIQUES
  {cat:'Technique',term:'Zodiacal Releasing',summary:'A Hellenistic time-lord technique that unfolds the life as nested chapters of varying lengths, measured from the Lot of Spirit (career and action) or the Lot of Fortune (body and circumstance). Each chapter is ruled by a sign and its lord; peak periods and Loosings of the Bond signal structural turning points.',source:'Vettius Valens, Anthology, Book IV (2nd c. CE)',lineage:'Hellenistic Alexandria → recovered by Schmidt and Hand (Project Hindsight, 1990s) → widely practiced post-2000.'},
  {cat:'Technique',term:'Firdaria',summary:'Persian-Arabic time-lord sequence in which each planet rules a fixed span of years in a set order — 70 years for the night chart, 75 for the day. Each period is subdivided into seven equal sub-periods cycling through the same planets.',source:'Abū Maʿshar, Book of the Revolutions of the Years of the World; later Latinised by Bonatti.',lineage:'Perso-Arabic synthesis (8th–9th c.) → medieval Latin astrology → still used in traditional Western practice today.'},
  {cat:'Technique',term:'Solar Return',summary:'A chart cast for the exact instant each year that the transiting Sun returns to its natal longitude. It is read as a sub-chart describing the character of the upcoming birthday-to-birthday year.',source:'Abū Maʿshar (9th c.); Morin de Villefranche, Astrologia Gallica (17th c.).',lineage:'Perso-Arabic origin → Latin → modern Placidean practice.'},
  {cat:'Technique',term:'Lunar Return',summary:'A chart cast for the instant the Moon returns to its natal longitude, repeating every ~27.3 days. Describes the texture of the coming lunar month.',source:'Morin, Astrologia Gallica (17th c.); developed in modern practice.',lineage:'Latin astrology → 20th c. revival by the Church of Light / Morinus school.'},
  {cat:'Technique',term:'Annual Profection',summary:'A traditional timing technique in which each year of life advances the Ascendant one sign. The sign reached becomes the year\'s Lord of the Time and colours that year\'s themes.',source:'Dorotheus of Sidon, Carmen Astrologicum (1st c. CE); Valens; Abū ʿAlī al-Khayyāt.',lineage:'Hellenistic → Perso-Arabic → Latin → Schmidt/Brennan revival.'},
  {cat:'Technique',term:'Planetary Hours',summary:'A division of day and night into twelve "hours" each, ruled in Chaldean order from the day\'s ruling planet at sunrise. Used in electional and magical contexts.',source:'Picatrix, Book III; Agrippa, Three Books of Occult Philosophy.',lineage:'Hellenistic through Picatrix (11th c. Arabic, Latin 13th c.) → Renaissance magic → modern Hermetic practice.'},
  {cat:'Technique',term:'Electional Astrology',summary:'Selecting an auspicious moment to begin an action by matching the intended work to favourable planetary hour, day, Moon condition, and freedom from afflictions (e.g., Void of Course, retrograde).',source:'Dorotheus, Carmen V; Bonatti, Liber Astronomiae; Lilly, Christian Astrology.',lineage:'Hellenistic → medieval Latin → early modern English traditional astrology.'},
  {cat:'Technique',term:'Sect',summary:'The division of planets by diurnal (day) and nocturnal (night) charts. Sun, Jupiter, Saturn are diurnal; Moon, Venus, Mars are nocturnal; Mercury takes sect from whichever light he is closer to by rising. In-sect planets behave more benevolently.',source:'Antiochus of Athens; Valens; Ptolemy, Tetrabiblos.',lineage:'Foundational Hellenistic doctrine, largely lost in medieval Latin practice, restored in modern Hellenistic revival.'},

  // OBJECTS
  {cat:'Object',term:'Lot of Fortune',summary:'Also "Pars Fortunae". A calculated point marking circumstance, body, and material well-being. Day formula: Asc + Moon − Sun. Night formula reverses: Asc + Sun − Moon.',source:'Valens, Anthology II; Paulus Alexandrinus; Abū Maʿshar.',lineage:'Hellenistic core → medieval → modern.'},
  {cat:'Object',term:'Lot of Spirit',summary:'A calculated point marking agency, action, vocation, and what the soul undertakes. Day: Asc + Sun − Moon. Night: reversed.',source:'Valens, Anthology II.IV–VI.',lineage:'Hellenistic → Schmidt\'s translation programme.'},
  {cat:'Object',term:'Seven Hermetic Lots',summary:'A traditional set of seven lots attributed to Hermes: Fortune, Spirit, Eros, Necessity, Courage, Victory, Nemesis. Each is derived from a pair of planets distanced from the Ascendant and reversed by sect.',source:'Paulus Alexandrinus, Introduction, ch. 23; attributed to Hermes Trismegistus.',lineage:'Hellenistic → Olympiodorus commentary → recovered through Project Hindsight.'},
  {cat:'Object',term:'Lunar Mansions',summary:'Twenty-eight divisions of the ecliptic based on the Moon\'s nightly travel (roughly 12°51\' each). Each mansion has traditional images, indications, and magical uses — especially in Picatrix and in the Arabic "Manāzil al-Qamar" system.',source:'Picatrix, Book IV; Agrippa, Book II, ch. 46.',lineage:'Indian Nakṣatras → Arabic Manāzil → Latin Picatrix → Renaissance magic.'},
  {cat:'Object',term:'Picatrix Faces (Decans)',summary:'The thirty-six divisions of ten degrees each along the zodiac. The Picatrix assigns each decan a talismanic image, a ruler (in Chaldean order), and a magical indication.',source:'Picatrix (Ghāyat al-Ḥakīm), Book II, ch. 11.',lineage:'Egyptian decans → Hellenistic → Arabic Picatrix → Latin 13th c. → Renaissance magic.'},
  {cat:'Object',term:'Essential Dignities',summary:'A system ranking each planet\'s condition by the degree it occupies: domicile, exaltation, triplicity, term (bound), and face. Each dignity carries traditional scoring.',source:'Ptolemy, Tetrabiblos I.17–23; Dorotheus I; Bonatti Liber Astronomiae.',lineage:'Hellenistic → Perso-Arabic → Latin → Lilly.'},
  {cat:'Object',term:'Void of Course Moon',summary:'The Moon is said to be "void of course" from the moment it perfects its last Ptolemaic aspect within a sign until it leaves the sign. Traditionally unfavourable for electing new undertakings.',source:'William Lilly, Christian Astrology I.110; Bonatti.',lineage:'Horary tradition (medieval Latin → 17th c. English).'},

  // CONCEPTS
  {cat:'Concept',term:'Peak Period (ZR)',summary:'Within Zodiacal Releasing, a subperiod whose sign is in an angular relationship (1st, 4th, 7th, 10th) to the starting sign of the major period. Peak periods are times of elevated public outcome and consequence.',source:'Valens, Anthology IV; modern elaboration by Chris Brennan, Demetra George.',lineage:'Hellenistic text → modern practice.'},
  {cat:'Concept',term:'Loosing of the Bond',summary:'In Zodiacal Releasing, a rupture that occurs when the next subperiod would fall in the eighth sign from the start. The sequence jumps instead to the ninth, marking a major life reorientation.',source:'Valens, Anthology IV.5–6.',lineage:'Hellenistic → recovered modern usage.'},
  {cat:'Concept',term:'Benefic / Malefic',summary:'Jupiter and Venus are benefics, Saturn and Mars malefics. The sect benefic (Venus by night, Jupiter by day) is most helpful; the out-of-sect malefic (Mars by day, Saturn by night) is most difficult.',source:'Ptolemy, Tetrabiblos I.5; Valens.',lineage:'Hellenistic core doctrine.'},
  {cat:'Concept',term:'Retrograde',summary:'The apparent backward motion of a planet as seen from Earth. Traditionally weakening or introverting the planet\'s significations; it does not reverse effects, but turns them inward.',source:'Ptolemy; Masha\'allah, On the Revolution of the Years of the World.',lineage:'Hellenistic → medieval → modern.'},
  {cat:'Concept',term:'Sect Light',summary:'The luminary that matches the chart\'s sect — Sun in a day chart, Moon in a night chart. Its condition is taken as the primary indicator of the native\'s overall fate and vitality.',source:'Valens, Anthology II; Porphyry, Introduction.',lineage:'Hellenistic foundational doctrine.'},

  // TRADITIONS
  {cat:'Tradition',term:'Hellenistic Astrology',summary:'The Greek-language astrological tradition from roughly the 1st c. BCE through the 7th c. CE, based in Alexandria. Systematised signs, houses, aspects, lots, time-lord techniques, and sect.',source:'Valens, Dorotheus, Ptolemy, Paulus, Porphyry, Hephaestio.',lineage:'Foundation of all subsequent Western astrology.'},
  {cat:'Tradition',term:'Perso-Arabic Astrology',summary:'The translation and elaboration of Hellenistic and Sassanid material in Abbasid Baghdad (8th–10th c.). Added firdaria, refined world-historical techniques, and transmitted Greek astrology to the Latin West.',source:'Abū Maʿshar, Masha\'allah, al-Kindi, al-Biruni.',lineage:'Sassanid Persian + Greek sources → Arabic → Latin 12th c.'},
  {cat:'Tradition',term:'Picatrix',summary:'The most important surviving text of medieval astrological magic: an Arabic grimoire (Ghāyat al-Ḥakīm, "The Aim of the Sage", c. 11th c.), translated to Latin in 1256. Covers planetary images, mansions, faces, talismans, and ritual.',source:'Ghāyat al-Ḥakīm / Picatrix (Arabic 11th c., Latin 13th c.).',lineage:'Sabian/Harranian syncretic magic → Arabic → Latin → Renaissance.'},
  {cat:'Tradition',term:'Hermetic Tradition',summary:'Texts attributed to Hermes Trismegistus — a syncretic Graeco-Egyptian sage — covering astrology, alchemy, and theurgy. Source of lots, decans, and much talismanic lore.',source:'Corpus Hermeticum; Asclepius; Liber Hermetis.',lineage:'Ptolemaic Egypt → late antiquity → Renaissance revival (Ficino).'},
  {cat:'Tradition',term:'Medieval Latin Astrology',summary:'The Latin synthesis (12th–17th c.) that produced Bonatti, Lilly, Morin. Emphasised horary, elections, nativities and annual revolutions using Hellenistic and Perso-Arabic material.',source:'Bonatti, Liber Astronomiae; Lilly, Christian Astrology; Morin, Astrologia Gallica.',lineage:'Latin translations of Arabic → European universities → early modern practice.'},

  // FIGURES
  {cat:'Figure',term:'Vettius Valens',summary:'Second-century Alexandrian astrologer whose nine-book Anthology is the most extensive surviving Hellenistic practical text. Primary source for Zodiacal Releasing, lots, and worked example charts.',source:'Anthology (Ἀνθολογίαι).',lineage:'Alexandrian school.'},
  {cat:'Figure',term:'Abū Maʿshar (Albumasar)',summary:'9th-century Persian astrologer of Baghdad. His Great Introduction and Book of Revolutions transmitted astrology to the Latin West and systematised firdaria and mundane techniques.',source:'Kitāb al-Madkhal al-Kabīr; Kitāb Taḥāwil Sinī al-ʿĀlam.',lineage:'Perso-Arabic → European medieval.'},
  {cat:'Figure',term:'Guido Bonatti',summary:'13th-century Italian astrologer, author of Liber Astronomiae — the encyclopaedic Latin summa of medieval astrology.',source:'Liber Astronomiae.',lineage:'Latin synthesis of Arabic sources.'},
  {cat:'Figure',term:'William Lilly',summary:'17th-century English astrologer whose Christian Astrology (1647) is the defining text of horary practice in English and a primary source for Void of Course doctrine.',source:'Christian Astrology.',lineage:'English traditional → modern horary revival.'},
  {cat:'Figure',term:'Hermes Trismegistus',summary:'Legendary Graeco-Egyptian sage, conflation of Hermes and Thoth, credited with the foundational Hermetic, alchemical, and astrological texts.',source:'Corpus Hermeticum; attribution of the Seven Lots, decans, and Liber Hermetis.',lineage:'Mythic attribution for an entire syncretic tradition.'},

  // ADDITIONAL TECHNIQUES
  {cat:'Technique',term:'Whole-Sign Houses',summary:'The oldest house system: each sign from the Ascendant sign onward equals one house. The Ascendant degree marks the rising point but does not define the house cusp. Simple, unambiguous, and the default in Hellenistic practice.',source:'Valens, Anthology; Paulus Alexandrinus; Dorotheus.',lineage:'Hellenistic standard → eclipsed by Placidus in 17th c. → restored in the Hellenistic revival (1990s onward).'},

  // ADDITIONAL OBJECTS
  {cat:'Object',term:'Fixed Stars',summary:'Bright stars near the ecliptic whose conjunctions to natal or transiting planets add vivid overtones to a reading. Each star carries its own nature — typically described as a blend of two planets (e.g., Regulus = Jupiter-Mars, Algol = Saturn-Jupiter).',source:'Ptolemy, Tetrabiblos I.9; Agrippa; Robson, Fixed Stars and Constellations (1923).',lineage:'Babylonian star lists → Hellenistic → medieval → Robson\'s modern catalogue.'},

  // ADDITIONAL CONCEPTS
  {cat:'Concept',term:'Applying and Separating Aspects',summary:'An applying aspect is one where the faster planet is moving toward exactitude with the slower — the event is approaching. A separating aspect has already perfected — the event is receding. Applying aspects carry more weight in prediction.',source:'Ptolemy, Tetrabiblos; Bonatti, Liber Astronomiae; Lilly, Christian Astrology.',lineage:'Hellenistic core → medieval horary emphasis → modern traditional practice.'},
  {cat:'Concept',term:'Dignity Scoring',summary:'A numerical method for assessing planetary strength: +5 for domicile, +4 for exaltation, +3 for triplicity, +2 for term/bound, +1 for face. Detriment and fall subtract. The total gives a quick snapshot of how well a planet can act.',source:'Ptolemy, Tetrabiblos I.17–23; Lilly\'s scoring table in Christian Astrology.',lineage:'Hellenistic dignities → medieval Latin scoring tables → Lilly\'s standardised point system.'},
  {cat:'Concept',term:'Orbs',summary:'The maximum distance in degrees at which an aspect is considered active. Traditional practice assigns orbs to planets (not aspects): Sun 15 degrees, Moon 12 degrees, others 7-8 degrees. Modern practice often uses tighter, aspect-based orbs.',source:'Lilly, Christian Astrology; Al-Biruni, Book of Instruction.',lineage:'Hellenistic → medieval planetary orbs → modern aspect-based orbs (a simplification).'},
  {cat:'Concept',term:'Synastry',summary:'Comparing two natal charts to assess relational dynamics. Look for conjunctions and hard aspects between personal planets, the condition of each person\'s 7th house ruler in the other\'s chart, and sect-light contacts.',source:'Ptolemy, Tetrabiblos IV.5; Dorotheus, Carmen; modern elaboration by Liz Greene and Robert Hand.',lineage:'Hellenistic compatibility techniques → medieval marriage elections → 20th c. psychological synastry.'},
  {cat:'Concept',term:'Derived Houses',summary:'A technique for reading one chart from multiple perspectives by rotating the house count. The 7th house becomes "the partner\'s 1st house", so the 8th is the partner\'s 2nd (their money), the 9th is their 3rd, and so on. Useful for horary and relational questions.',source:'Bonatti, Liber Astronomiae; Lilly, Christian Astrology III.',lineage:'Medieval horary innovation → standard practice in traditional Western astrology.'}
];
